dados = {
    "sintomas": [
        "Febre alta Dores de cabeca Rigidez no pescoco Nauseas",
        "Fadiga cronica Falta de ar Palpitacoes Tontura",
        "Tosse persistente Febre Sudorese noturna Perda de peso",
        "Dor abdominal intensa Febre Diarreia sanguinolenta",
        "Sede excessiva Perda de peso Miccao frequente",
        "Dores articulares Erupcao cutanea em formato de borboleta no rosto Fadiga",
        "Dor no peito Falta de ar Suor excessivo Tontura",
        "Coceira intensa Erupcoes cutaneas Pequenas bolhas na pele",
        "Perda de memoria Desorientacao Dificuldade de comunicacao",
        "Fadiga extrema Dor muscular Febre Dor de garganta",
        "Dor de cabeça Congestao nasal Febre Dor muscular",
        "Diarreia aquosa Colicas abdominais Vomitos Desidratacao",
        "Tosse com chiado Falta de ar Aperto no peito",
        "Dificuldade para engolir Azia Regurgitacao acida",
        "Manchas vermelhas com coceira Febre Dor de cabeça Dor muscular",
        "Cansaco Ictericia Dores abdominais",
        "Dor nas costas Dor irradiada para as pernas Dificuldade para andar",
        "Aumento da frequencia urinaria Dor ao urinar Febre",
        "Tontura Zumbido no ouvido Perda auditiva",
        "Alteracoes de humor Tristeza profunda Falta de interesse em atividades",
    ],
    "doenca": ["Meningite", "Anemia", "Tuberculose", "Doenca de Crohn",
               "Diabetes mellitus", "Lupus", "Infarto do miocardio",
               "Dermatite atopica", "Alzheimer", "Mononucleose",
               "Influenza", "Gastroenterite viral", "Asma",
               "Doenca do refluxo gastroesofagico", "Sarampo",
               "Hepatite", "Hernia de disco", "Infeccao urinaria",
               "Doenca de Meniere", "Depressao"]
}